'use strict'

module.exports = {
  // discovery
  NAMESPACE_DISCOVERY: 'Alexa.Discovery',

  // powercontrol
  NAMESPACE_POWERCONTROL: 'Alexa.PowerController',
  NAME_TURNON: 'TurnOn',
  NAME_TURNOFF: 'TurnOff',

  // brightness
  NAMESPACE_BRIGHTNESSCONTROLLER: 'Alexa.BrightnessController',
  NAME_ADJUSTBRIGHTNESS: 'AdjustBrightness',
  NAME_SETBRIGHTNESS: 'SetBrightness',

  // camera
  NAMESPACE_CAMERASTREAMCONTROLLER: 'Alexa.CameraStreamController',
  NAME_INITIALIZECAMERASTREAM: 'InitializeCameraStreams',

  // thermostat
  NAMESPACE_THERMOSTATCONTROLLER: 'Alexa.ThermostatController',
  NAME_ADJUSTTARGETTEMPERATURE: 'AdjustTargetTemperature',
  NAME_SETTARGETTEMPERATURE: 'SetTargetTemperature',
  NAME_SETTHERMOSTATMODE: 'SetThermostatMode',

  // authorization
  NAMESPACE_AUTHORIZATION: 'Alexa.Authorization',
  NAME_ACCEPTGRANT: 'AcceptGrant',

  // Scene
  NAMESPACE_SCENECONTROLLER: 'Alexa.SceneController',
  NAME_ACTIVATIONSTARTED: 'ActivationStarted',
  NAME_DEACTIVATIONSTARTED: 'DeactivationStarted',
  // error
  ERR_BRIDGE_UNREACHABLE: 'BRIDGE_UNREACHABLE',
  ERR_ENDPOINT_BUSY: 'ENDPOINT_BUSY',
  ERR_ENDPOINT_LOW_POWER: 'ENDPOINT_LOW_POWER',
  ERR_ENDPOINT_UNREACHABLE: 'ENDPOINT_UNREACHABLE',
  ERR_EXPIRED_AUTHORIZATION_CREDENTIAL: 'EXPIRED_AUTHORIZATION_CREDENTIAL',
  ERR_FIRMWARE_OUT_OF_DATE: 'FIRMWARE_OUT_OF_DATE',
  ERR_HARDWARE_MALFUNCTION: 'HARDWARE_MALFUNCTION',
  ERR_INTERNAL_ERROR: 'INTERNAL_ERROR',
  ERR_INVALID_AUTHORIZATION_CREDENTIAL: 'INVALID_AUTHORIZATION_CREDENTIAL',
  ERR_INVALID_DIRECTIVE: 'INVALID_DIRECTIVE',
  ERR_INVALID_VALUE: 'INVALID_VALUE',
  ERR_NO_SUCH_ENDPOINT: 'NO_SUCH_ENDPOINT',
  ERR_RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  ERR_ACCEPT_GRANT_FAILED: 'ACCEPT_GRANT_FAILED'
}
