'use strict'

module.exports = {
  // discovery
  NAMESPACE_DISCOVERY: 'Alexa.Discovery',

  // powercontrol
  NAMESPACE_POWERCONTROL: 'Alexa.PowerController',
  NAME_TURNON: 'TurnOn',
  NAME_TURNOFF: 'TurnOff',

  // brightness
  NAMESPACE_BRIGHTNESSCONTROLLER: 'Alexa.BrightnessController',
  NAME_ADJUSTBRIGHTNESS: 'AdjustBrightness',
  NAME_SETBRIGHTNESS: 'SetBrightness',
  // set color
  NAMESPACE_COLORCONTROLLER: 'Alexa.ColorController',
  NAME_SETCOLOR: 'SetColor',
  // set color temperature
  NAMESPACE_COLOR_TEMPERATURE_CONTROLLER: 'Alexa.ColorTemperatureController',
  NAME_INCREASE_COLOR_TEMPERATURE: 'IncreaseColorTemperature',
  NAME_DECREASE_COLOR_TEMPERATURE: 'DecreaseColorTemperature',
  NAME_SET_COLOR_TEMPERATURE: 'SetColorTemperature',

  // camera
  NAMESPACE_CAMERASTREAMCONTROLLER: 'Alexa.CameraStreamController',
  NAME_INITIALIZECAMERASTREAM: 'InitializeCameraStreams',

  // thermostat
  NAMESPACE_THERMOSTATCONTROLLER: 'Alexa.ThermostatController',
  NAME_ADJUSTTARGETTEMPERATURE: 'AdjustTargetTemperature',
  NAME_SETTARGETTEMPERATURE: 'SetTargetTemperature',
  NAME_SETTHERMOSTATMODE: 'SetThermostatMode',

  // channel
  NAMESPACE_CHANNELCONTROLLER: 'Alexa.ChannelController',
  NAME_CHANGECHANNEL: 'ChangeChannel',
  NAME_SKIPCHANNELS: 'SkipChannels',

  // speaker
  NAMESPACE_SPEAKER: 'Alexa.Speaker',
  NAME_SETVOLUME: 'SetVolume',
  NAME_ADJUSTVOLUME: 'AdjustVolume',
  NAME_SETMUTE: 'SetMute',

  // step speaker
  NAMESPACE_STEPSPEAKER: 'Alexa.StepSpeaker',

  // playback
  NAMESPACE_PLAYBACKCONTROLLER: 'Alexa.PlaybackController',
  NAME_FASTFORWARD: 'FastForward',
  NAME_NEXT: 'Next',
  NAME_PAUSE: 'Pause',
  NAME_PLAY: 'Play',
  NAME_PREVIOUS: 'Previous',
  NAME_REWIND: 'Rewind',
  NAME_STARTOVER: 'StartOver',
  NAME_STOP: 'Stop',

  // input
  NAMESPACE_INPUTCONTROLLER: 'Alexa.InputController',
  NAME_SELECTINPUT: 'SelectInput',

  // authorization
  NAMESPACE_AUTHORIZATION: 'Alexa.Authorization',
  NAME_ACCEPTGRANT: 'AcceptGrant',

  // Scene
  NAMESPACE_SCENECONTROLLER: 'Alexa.SceneController',
  NAME_ACTIVATE: 'Activate',
  NAME_DEACTIVATE: 'Deactivate',
  // Lock
  NAMESPACE_LOCKCONTROLLER: 'Alexa.LockController',
  NAME_LOCK: 'Lock',
  NAME_UNLOCK: 'Unlock',
  // Lock
  NAMESPACE_REPORT_STATE: 'Alexa',
  NAME_REPORT_STATE: 'ReportState',
  // error
  ERR_ALREADY_IN_OPERATION: 'ALREADY_IN_OPERATION',
  ERR_BRIDGE_UNREACHABLE: 'BRIDGE_UNREACHABLE',
  ERR_ENDPOINT_BUSY: 'ENDPOINT_BUSY',
  ERR_ENDPOINT_LOW_POWER: 'ENDPOINT_LOW_POWER',
  ERR_ENDPOINT_UNREACHABLE: 'ENDPOINT_UNREACHABLE',
  ERR_EXPIRED_AUTHORIZATION_CREDENTIAL: 'EXPIRED_AUTHORIZATION_CREDENTIAL',
  ERR_FIRMWARE_OUT_OF_DATE: 'FIRMWARE_OUT_OF_DATE',
  ERR_HARDWARE_MALFUNCTION: 'HARDWARE_MALFUNCTION',
  ERR_INTERNAL_ERROR: 'INTERNAL_ERROR',
  ERR_INVALID_AUTHORIZATION_CREDENTIAL: 'INVALID_AUTHORIZATION_CREDENTIAL',
  ERR_INVALID_DIRECTIVE: 'INVALID_DIRECTIVE',
  ERR_INVALID_VALUE: 'INVALID_VALUE',
  ERR_NO_SUCH_ENDPOINT: 'NO_SUCH_ENDPOINT',
  ERR_NOT_CALIBRATED: 'NOT_CALIBRATED',
  ERR_NOT_SUPPORTED_IN_CURRENT_MODE: 'NOT_SUPPORTED_IN_CURRENT_MODE',
  ERR_NOT_IN_OPERATION: 'NOT_IN_OPERATION',
  ERR_POWER_LEVEL_NOT_SUPPORTED: 'POWER_LEVEL_NOT_SUPPORTED',
  ERR_RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  ERR_VALUE_OUT_OF_RANGE: 'VALUE_OUT_OF_RANGE',
  ERR_TEMPERATURE_VALUE_OUT_OF_RANGE: 'TEMPERATURE_VALUE_OUT_OF_RANGE',
  ERR_ACCEPT_GRANT_FAILED: 'ACCEPT_GRANT_FAILED'
}
